include(CMakePrintHelpers)

function(lokimon_print_variables_with_pattern pattern)
  get_cmake_property(_variableNames VARIABLES)
  list(SORT _variableNames)
  foreach (_variableName ${_variableNames})
    unset(MATCHED)
    string(REGEX MATCH ${pattern} MATCHED ${_variableName})
    if (NOT MATCHED)
      continue()
    endif ()
    cmake_print_variables(${_variableName})
  endforeach ()
endfunction()